apiVersion: v1
kind: Secret
metadata:
  name: vkbot-secret
  namespace: vkbot
type: Opaque
stringData:
  VK_TOKEN: "vk1.a.xxxx"
  VK_SECRET_KEY: "xxxx"
  OPENAI_API_KEY: "sk-xxxx"
  VOISPARK_API_KEY: "xxxx"
  GOOGLE_API_KEY: "xxxx"
  KINESCOPE_API_KEY: "xxxx"

